Feature/192
fixadate/fixadate_backend pull request #196
Opened 2024-08-10 15:35 UTC by YongGoose

## 📄 작업 내용 요약

## 📎 Issue 번호

- close #{Issue 번호}

## 📌 PR 유형

어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## ✅ PR Checklist

PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-08-14 17:58 UTC, JJ503 requested changes
리팩터링 및 테스트 고생 많으셨습니다!
리팩터링 과정에서 네이밍 변경 등으로 인해 files changed가 많아졌다고 해주셨기에 코드 리뷰에 있어 memeber 도메인 관련해서만 집중적으로 봤습니다.
리뷰 대부분은 의견 질문 및 컨벤션 관련입니다.

2024-08-14 17:58 UTC, JJ503 commented on src/main/java/com/fixadate/global/facade/MemberFacade.java
해당 클래스에서는 컨벤션들이 적용되지 않은 부분들이 있네요!
그런데, 로직상 변경이 생긴 것일 뿐 이번 pr 리팩터링 범위에 포함되지 않는다면 넘겨주세요.

2024-08-14 17:58 UTC, JJ503 commented on src/main/java/com/fixadate/domain/member/service/MemberService.java
> +		List<String> nouns = List.of(this.nouns.split(","));
내부 변수들은 final을 붙이지 않아도 될까요?

2024-08-14 17:58 UTC, JJ503 commented on src/main/java/com/fixadate/global/jwt/service/JwtProvider.java
> +																				NOT_FOUND_MEMBER_IDENTIFIER));
```suggestion
Member member = memberRepository.findMemberById(id)
										.orElseThrow(() -> new TokenException(NOT_FOUND_MEMBER_IDENTIFIER));
```

개행이 위와 같이 이루어지면 좋겠네요!
(변경 외 부분이 있어 블록이 잡히지 않아 요상하게 선택됐습니다 ... 🥲)

2024-08-14 17:58 UTC, JJ503 commented on src/test/java/com/fixadate/config/LocalStackContainerProvider.java
> +	private static final DockerImageName DOCKER_IMAGE_NAME = DockerImageName.parse("localstack/localstack:0.12.18");
개행이 누락됐네요!

2024-08-14 17:58 UTC, JJ503 commented on src/test/java/com/fixadate/config/LocalStackContainerProvider.java
> +			.withServices(LocalStackContainer.Service.S3);
개행이 필요 없을 것 같습니다.
또한, S3만 남기고 import문으로 옮기면 이해가 어려울까요?

2024-08-14 17:58 UTC, JJ503 commented on src/test/java/com/fixadate/config/LocalStackContainerProvider.java
해당 클래스에서 전체적으로 final이 누락됐습니다!

2024-08-14 17:58 UTC, JJ503 commented on src/test/java/com/fixadate/config/RedisContainerProvider.java
> +			.withExposedPorts(REDIS_PORT);
여기도 개행이 불필요하다고 생각하는데 어떻게 생각하시나요?

2024-08-14 17:58 UTC, JJ503 commented on src/test/java/com/fixadate/domain/member/controller/impl/MemberControllerImplTest.java
> +	MockMvc mockMvc;
private이 추가되면 좋겠네요!

2024-08-14 17:58 UTC, JJ503 commented on src/test/java/com/fixadate/domain/member/controller/impl/MemberControllerImplTest.java
> +		void 멤버_정보_수정() throws Exception {
개행이 누락됐네요!

2024-08-14 17:58 UTC, JJ503 commented on src/test/java/com/fixadate/domain/member/controller/impl/MemberControllerImplTest.java
컨트롤러 테스트에서는 feature class, fixture monkey를 사용하지 않은 이유가 있을까요?

2024-08-14 17:58 UTC, JJ503 commented on src/test/java/com/fixadate/domain/member/repository/MemberJpaRepositoryTest.java
> +		assertThat(actual).contains(저장된_멤버);
여러가지를 테스트해야 할 때 `SoftAssertions`를 사용하는 것에 대해 어떻게 생각하시나요?

2024-08-15 02:56 UTC, JJ503 commented on src/main/java/com/fixadate/domain/member/service/repository/MemberRepository.java
> +	void delete(Member member);
추가로 ","와 같은 매직 넘버, 매직 리터럴들은 변경되어선 안 되기도 하고 봤을 때 어떤 것을 의미하는지 바로 알기 어렵기도 합니다.
그래서 이러한 부분들을 상수로 치환해 수정을 용이하게 해 준다는 장점이 있습니다.
혹시 어떻게 생각하시나요?

2024-08-15 02:56 UTC, JJ503 commented on src/main/java/com/fixadate/domain/member/service/MemberService.java
> +		List<String> nouns = List.of(this.nouns.split(","));
추가로 ","와 같은 매직 넘버, 매직 리터럴들은 변경되어선 안 되기도 하고 봤을 때 어떤 것을 의미하는지 바로 알기 어렵기도 합니다.
그래서 이러한 부분들을 상수로 치환해 수정을 용이하게 해 준다는 장점이 있습니다.
혹시 어떻게 생각하시나요?

2024-08-15 04:18 UTC, YongGoose commented on src/main/java/com/fixadate/domain/member/entity/Member.java
> `@AllArgsConstructor`를 사용하면, id까지 포함되어 버리지 않나요??

넵 맞습니다! 

위 어노테이션을 추가한 이유로는 @Builder 어노테이션을 사용하려면 @AllArgsConstructor 어노테이션을 통해 모든 파라미터를 가진 생성자를 생성해야 해서 추가했습니다.

물론 모든 멤버 변수가 매개변수로 있는 생성자를 직접 생성하는 방법으로 대체 가능하긴 하나, 필요성을 못 느껴 어노테이션으로 대체했습니다.

---
> If you do have an explicit constructor, put the @Builder annotation on the constructor instead of on the class.

공식문서에 따르면 명시적인 생성자를 생성한 경우, 클래스가 아닌 생성자에 @Builder 어노테이션을 붙이는 방법으로 가능한 것 같기도 합니다.

- @JJ503 생성자에서 id를 제외해야 하는 강력한 이유라도 있는지 여쭤봐도 될까요? 
만약 이유가 타당하다면 생성자에 @builder 어노테이션을 붙이는 방법으로 진행 해보려고 합니다.

참고 문서 : https://projectlombok.org/features/Builder

2024-08-15 04:21 UTC, YongGoose commented on src/main/java/com/fixadate/domain/member/entity/Member.java
> 추가로 별건 아니지만, Getter와 같은 어노테이션은 아래로 내리는 것에 대해 어떻게 생각하시나요?
> lombok을 사용하지 않고 직접 해당 코드를 작성할 때 보통 equals&hashcode나 getter는 하위로 내리는 것으로 알고 있습니다.
> lombok 등을 사용한 어노테이션도 비슷한 순서로 가면 어떨까 해 의견드립니다!

lombok 어노테이션의 경우 저도 동의합니다.

Member 엔티티의 경우 JPA, Lombok, Jackson 라이브러리의 어노테이션이 사용되었는데 어노테이션 관련 컨벤션을 정하는 것도 좋을 것 같다는 생각이 듭니다!

- ex) JPA - Lombok - Jackson 순으로 나열

2024-08-15 04:41 UTC, YongGoose commented on src/main/java/com/fixadate/domain/member/entity/Member.java
> +	public String getUsername() {
> 그리고 아래 `is~` 메서드들은 어디에 사용되는 것일까요? 하드코딩된 상태로 사용되어도 괜찮은 것인지 궁금합니다!
> 
> 또한, Member가 UserDetail를 상속받는 이유가 무엇인가요? 이게 Spring Security 때문인 것일까요?

넵 맞습니다. 
Spring Security을 위해 구현을 했습니다.

- 코드를 보시다가 궁금한 점이 생길 수 있어 미리 말씀 드립니다!
현재 MemberService를 보면 loadByUsername 이라는 메서드가 null을 반환하도록 구현 되어 있는데 이는 저희가 jwt를 이용해 인증을 하기 때문에 사용을 하지 않아 null을 반환하도록 구현한 것입니다.

---

is와 같은 메서드들은 사용자를 제어하기 위해 존재하는 메서드 들이라고 생각하시면 됩니다!
현재 Fixadate에서는 admin 관련 기획 / 로직이 없어 하드 코딩으로 구현했고 추후에 기획 / 로직이 구현되면 변경할 계획입니다!

2024-08-15 04:43 UTC, YongGoose commented on src/main/java/com/fixadate/domain/member/entity/Member.java
> +	public String getUsername() {
> 추가로 통일성 있게, 해당 클래스의 필드를 사용하는 것이라면 `this`를 붙여주는 것에 대해 어떻게 생각하시나요?

하기와 같이 변경하면 될까요?

```
	@Override
	public String getUsername() {
		return this.name;
	}
```

2024-08-15 04:53 UTC, YongGoose commented on src/main/java/com/fixadate/domain/member/repository/MemberRepositoryImpl.java
> +	}
이걸 놓쳤네요...!

지적 감사합니다 :) 저장한 객체를 반환 해주는 것이 맞습니다.

2024-08-15 04:58 UTC, YongGoose commented on src/main/java/com/fixadate/domain/member/service/MemberService.java
> +		return strings.get(current().nextInt(strings.size())).trim();
FixtureMonkey의 Randoms 클래스에서 current라는 메서드를 통해 Random 객체를 반환 해, 지어보았습니다!
```
	public static Random current() {
		return USE_JQWIK_ENGINE
			? SourceOfRandomness.current()
			: CURRENT.get();
	}
```

---

하지만 전체적인 코드를 보니, 현재 스레드와 관련된 `Random` 객체를 반환하는 역할을 해서 current로 지었네요..

getRandom으로 지으려고 하는데 어떻게 생각하시나요?
```
	public static Random getRandom() {
		return RANDOM;
	}
```

2024-08-15 05:07 UTC, YongGoose commented on src/main/java/com/fixadate/domain/member/service/MemberService.java
> +		List<String> nouns = List.of(this.nouns.split(","));
> 추가로 ","와 같은 매직 넘버, 매직 리터럴들은 변경되어선 안 되기도 하고 봤을 때 어떤 것을 의미하는지 바로 알기 어렵기도 합니다. 그래서 이러한 부분들을 상수로 치환해 수정을 용이하게 해 준다는 장점이 있습니다. 혹시 어떻게 생각하시나요?

좋은 것 같습니다 :-)

유지보수 관점에서 매우 좋은 생각이네요.

2024-08-15 05:10 UTC, YongGoose commented on src/main/java/com/fixadate/domain/member/service/MemberService.java
> +		List<String> nouns = List.of(this.nouns.split(","));
> 내부 변수들은 final을 붙이지 않아도 될까요?

저희가 final을 붙이는 것을 컨벤션으로 정한 만큼, 붙이는게 좋을 것 같습니다!
안전성 관점에서도 붙이는게 좋을 것 같네요..!

2024-08-15 05:12 UTC, YongGoose commented on src/main/java/com/fixadate/global/jwt/service/JwtProvider.java
> +																				NOT_FOUND_MEMBER_IDENTIFIER));
너무 길어져 하기와 같이 변경하겠습니다!

```
		Member member = memberRepository.findMemberById(id).orElseThrow(
			() -> new TokenException(NOT_FOUND_MEMBER_IDENTIFIER)
		);
```

2024-08-15 05:15 UTC, YongGoose commented on src/test/java/com/fixadate/config/LocalStackContainerProvider.java
> +			.withServices(LocalStackContainer.Service.S3);
> 또한, S3만 남기고 import문으로 옮기면 이해가 어려울까요?

하기와 같이 변경하는 것이 맞을까요?

```
	private static final DockerImageName DOCKER_IMAGE_NAME = DockerImageName.parse("localstack/localstack:0.12.18");
	private static final LocalStackContainer LOCAL_STACK_CONTAINER = new LocalStackContainer(DOCKER_IMAGE_NAME);

	@Value("${cloud.aws.bucket-name}")
	private String bucket;

	@Bean(initMethod = "start", destroyMethod = "stop")
	public LocalStackContainer localStackContainer() {
		return LOCAL_STACK_CONTAINER.withServices(LocalStackContainer.Service.S3);
	}
```

2024-08-15 05:28 UTC, YongGoose commented on src/test/java/com/fixadate/domain/member/controller/impl/MemberControllerImplTest.java
자바에서는 다중 상속이 불가능해 사용하지 않았습니다.
- 조금 더 자세히 말씀드리면 `MemberControllerImplTest` 가 상속하고 있는 `CommonControllerSliceTest`에서 fixture를 정의하게 되면 common 클래스가 너무 비대해질까봐 정의하지 않았습니다.

`Fixture class`에서 `CommonControllerSliceTest`을 상속하고 `Test 클래스`에서 `Fixture class`를 상속하는 방법도 있겠네요.

2024-08-15 06:06 UTC, YongGoose commented on src/test/java/com/fixadate/domain/member/service/fixture/MemberServiceFixture.java
> +	private static final FixtureMonkey DTO_몽키 = FixtureMonkeyConfig.jakartaValidationMonkey();
맞습니다. 저도 동일하게 정적 변수는 상단으로 올립니다!

지적 감사합니다 :)

2024-08-15 06:06 UTC, YongGoose commented on src/test/java/com/fixadate/domain/member/repository/MemberJpaRepositoryTest.java
> +		assertThat(actual).contains(저장된_멤버);
하나의 Assertion이 실패하더라도 결과를 저장한다는 점에서 좋은 것 같습니다.

수정하도록 하겠습니다!

2024-08-15 15:29 UTC, JJ503 commented on src/main/java/com/fixadate/domain/member/entity/Member.java
> Member 엔티티의 경우 JPA, Lombok, Jackson 라이브러리의 어노테이션이 사용되었는데 어노테이션 관련 컨벤션을 정하는 것도 좋을 것 같다는 생각이 듭니다!

개인적으로는 현재 상태에서 getter와 equals&hashcode가 가장 하단에 있었으면 합니다!

2024-08-15 15:29 UTC, JJ503 commented on src/main/java/com/fixadate/domain/member/entity/Member.java
> 생성자에서 id를 제외해야 하는 강력한 이유라도 있는지 여쭤봐도 될까요?

id를 사용자가 직접 설정할 수도 있는 상황이 벌어지는 것이 좋지 않다고 생각했습니다.
id의 경우 무조건 적으로 자동으로 생성된 값을 사용해야 하기에, 의도와 상관없이 사용될 가능성도 있으며 굳이 id를 직접 설정할만한 여지 자체를 줄 필요가 없다고 생각했습니다.

2024-08-15 15:30 UTC, JJ503 commented on src/main/java/com/fixadate/domain/member/entity/Member.java
> +	public String getUsername() {
> 하기와 같이 변경하면 될까요?

네 제가 생각한 방식과 동일합니다!

2024-08-15 15:31 UTC, JJ503 commented on src/main/java/com/fixadate/domain/member/entity/Member.java
> +	public String getUsername() {
> 코드를 보시다가 궁금한 점이 생길 수 있어 미리 말씀드립니다!

아직 Spring Security에 대한 개념을 잘 몰라 헷갈리네요..! 답변 감사합니다!

2024-08-15 15:38 UTC, JJ503 commented on src/main/java/com/fixadate/domain/member/service/MemberService.java
> +		return strings.get(current().nextInt(strings.size())).trim();
`RANDOM`을 반환하는 것은 `new Random()`을 상수로 저장해 반환해 주는 것을 의미하는 것일까요?
만약 그렇다면, 그냥 랜덤 값을 반환해 주는 것은 어떨까요?
현재처럼 특정 크기의 랜덤이 필요한 것이라면 크기 값을 넘겨 해당 크기만큼의 랜덤 값들을 반환받으면 랜덤 관련 로직을 좀 더 독립적으로 사용할 수 있지 않을까 싶습니다!
나중에 랜덤 값 하나만 필요한 상황이라면 파라미터가 없는 메서드도 만들어 오버로딩해 사용할 수도 있으니 괜찮지 않을까 싶어 제안드립니다!

2024-08-15 15:41 UTC, JJ503 commented on src/main/java/com/fixadate/domain/member/service/MemberService.java
> +		List<String> nouns = List.of(this.nouns.split(","));
<img width="365" alt="image" src="https://github.com/user-attachments/assets/9a700d37-c623-478e-9a9a-b465679d79c1">
mac 기준 option+command+v를 통해 자동 변수 설정 시 위와 같이 설정 아이콘이 뜨는데 해당 아이콘을 클릭해 `Declare final`을 체크해 주시면 자동으로 final이 붙습니다!

2024-08-15 15:47 UTC, JJ503 commented on src/test/java/com/fixadate/config/LocalStackContainerProvider.java
> +			.withServices(LocalStackContainer.Service.S3);
```
    @Bean(initMethod = "start", destroyMethod = "stop")
    public LocalStackContainer localStackContainer() {
        return new LocalStackContainer(DOCKER_IMAGE_NAME).withServices(S3);
    }
```

위와 같이 변경하는 것을 의미한 것이었습니다!
`LocalStackContainer.Service` 해당 부분은 import 문에 추가하고요!

2024-08-15 15:54 UTC, JJ503 commented on src/test/java/com/fixadate/domain/member/controller/impl/MemberControllerImplTest.java
> Fixture class에서 CommonControllerSliceTest을 상속하고 Test 클래스에서 Fixture class를 상속하는 방법도 있겠네요.

저도 이 방식을 생각하고 말씀드리긴 했습니다!
혹은, `@Componet`를 통해 빈으로 주입시키는 것은 어떠신가요?

2024-08-16 01:20 UTC, JJ503 commented on src/main/java/com/fixadate/domain/member/controller/impl/MemberControllerImpl.java
> +	public ResponseEntity<MemberInfoResponse> getMemberInfo(@PathVariable final String memberId) {
api 규격서를 통해 mypage의 경우도 위 api를 사용하는 것으로 보았습니다.
그런데, 마이 페이지 조회 시 url id가 포함되는 게 좋을지 의문입니다.

추후 다른 사람의 프로필도 볼 수 있게 된다면, 마이 페이지와 다른 사람의 프로필 정보는 서로 다른 정보를 전달할 것이라 생각합니다.
그래서 다른 사람의 프로필 조회 시에는 위와 같은 방식을 사용해도 괜찮지만, 마이 페이지 조회 시에는 인가 과정도 필요하기에 이때 사용자 정보도 생길 것입니다.
그래서 api를 서로 구분하기 위해 `/v1/member`로 url을 설정한 후 `memberId`는 인가를 통해 발생된 정보를 통해 가져오는 것에 대해 어떻게 생각하시는 지 궁금합니다. 아래 update 관련도 동일하게 생각합니다.

물론 인증/인가 방식이 바뀌면서 바뀔 수도 있지만, 미리 의견 드려봅니다.

2024-08-16 01:44 UTC, YongGoose commented on src/main/java/com/fixadate/domain/member/controller/impl/MemberControllerImpl.java
> +	public ResponseEntity<MemberInfoResponse> getMemberInfo(@PathVariable final String memberId) {
@JJ503 
그러네요.
현재 getMemberInfo와 updateMemberInfo는 본인의 정보를 조회 / 수정하는 것인데 파라미터로 memberId를 받게되면 다른 사람의 정보를 조회 / 수정 할 수 있을 것 같습니다.

현재 가능한 방법으로는 인증을 통해 생성되는 Principal을 이용해 접근하는 것입니다.
그렇게 된다면 memberId를 받지 않고, 현재 인증에서 사용되는 Jwt 인증 과정에서 생성되는 멤버의 정보를 토대로 조회 / 수정을 할 수 있게 됩니다.

--- 

추가적인 이야기로 제가 Discussion에 `@AuthenticationPrincipal`을 대체하는 방법을 작성해놓긴 했는데 웬만하면 대체를 하지 않는 방법으로 가는 것이 좋을 것 같습니다.
`@AuthenticationPrincipal` 어노테이션은 `SecurityContextHolder`에 저장된 정보를 가지고 오는데 다른 인증 방식을 사용한다고 해서 `SecurityContextHolder`에 정보를 저장하지 않는건 아니여서 아마 그대로 사용 가능할 것 같습니다.

현재는 JwtAuthenticationFilter에서 SecurityContextHolder에 정보를 저장하고 있습니다.
```
	@Override
	protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
		throws ServletException, IOException, MalformedJwtException {
		String jwt = jwtProvider.retrieveToken(request);
		if (StringUtils.hasText(jwt) && jwtProvider.validateToken(jwt) && !jwtProvider.isTokenBlackList(jwt)) {
			SecurityContextHolder
				.getContext()
				.setAuthentication(
					jwtProvider.getAuthentication(jwt)
				);
		}
		filterChain.doFilter(request, response);
	}
```

하기의 링크는 제가 새로운 인증 방식에 대해 간단하게 생각해본 글입니다!
아직 최종 아이디어는 아니며, 여기서 더 보완을 할 생각입니다.

한번 참고하시는 것도 좋을 것 같아서 보냅니다 :)
https://yong-jun.notion.site/a786e296a9ec4bf7a8f79156bdd3f72e?pvs=4

2024-08-16 01:47 UTC, YongGoose commented on src/main/java/com/fixadate/domain/member/entity/Member.java
> > 생성자에서 id를 제외해야 하는 강력한 이유라도 있는지 여쭤봐도 될까요?
> 
> id를 사용자가 직접 설정할 수도 있는 상황이 벌어지는 것이 좋지 않다고 생각했습니다. id의 경우 무조건 적으로 자동으로 생성된 값을 사용해야 하기에, 의도와 상관없이 사용될 가능성도 있으며 굳이 id를 직접 설정할만한 여지 자체를 줄 필요가 없다고 생각했습니다.

음.. 좋은 이유인 것 같습니다!
@AllArgsConstructor 어노테이션과 @builder 어노테이션을 클래스단에서 제거한 뒤, id를 제외한 값을 파라미터로 가지고 있는 생성자를 생성한 뒤 해당 메서드에 @builder 어노테이션을 붙이는 방향으로 진행하겠습니다!

2024-08-16 01:50 UTC, YongGoose commented on src/test/java/com/fixadate/domain/member/controller/impl/MemberControllerImplTest.java
> > Fixture class에서 CommonControllerSliceTest을 상속하고 Test 클래스에서 Fixture class를 상속하는 방법도 있겠네요.
> 
> 저도 이 방식을 생각하고 말씀드리긴 했습니다! 혹은, `@Componet`를 통해 빈으로 주입시키는 것은 어떠신가요? 그렇다면 상속 없이 더 편하게 사용할 수 있지 않을까 싶어 제안드립니다!

혹시 조금 더 자세하게 설명 부탁드려도 될까요?

2024-08-16 01:53 UTC, YongGoose commented on src/main/java/com/fixadate/domain/member/service/MemberService.java
> +		return strings.get(current().nextInt(strings.size())).trim();
좋은 방법인 것 같습니다!

어차피 인스턴스가 하나인 것은 보장되므로, 상관 없을 것 같네요.
하기와 같이 구현을 해보려고 하는데 어떠신가요?
```
	public static int getRandomInt() {
		return RANDOM.nextInt();
	}
```

2024-08-16 14:58 UTC, JJ503 commented on src/test/java/com/fixadate/domain/member/controller/impl/MemberControllerImplTest.java
CommonControllerSliceTest에 @Component를 달아 Bean으로 생성한 뒤 이를 사용해야 하는 곳에 @Autowired를 통해 주입받는 것을 말씀드렸습니다!
다만, 이를 통해서는 필드 값을 가져올 수는 없기에 getter로 가져와서 사용하면 어떨까 싶었습니다.
조금 번거롭더라도 상속을 피할 수 있는 방법이기에 제안드립니다.

2024-08-17 02:17 UTC, JJ503 commented on src/main/java/com/fixadate/domain/member/entity/Member.java
> +	public Member(
Builder만 사용할 것이기에 `private`로 변경해 줘도 괜찮겠네요!

2024-08-17 02:26 UTC, JJ503 commented on src/main/java/com/fixadate/domain/member/entity/Member.java
> +@Getter
@ToString을 추가하는 것에 대해 어떻게 생각하시나요?
추가하면 디버깅을 할 때 좀 더 편하지 않을까 싶어 제안드립니다!
그리고 추가하게 된다면, n+1 문제를 피하기 위해 연관관계로 묶여있는 필드는 제외해야 할 텐데, 제외하는 exclude를 사용할지 toString에 사용할 필드만 설정하는 of를 사용하면 좋을지 이야기해 보면 좋겠네요.

2024-08-17 07:05 UTC, YongGoose commented on src/main/java/com/fixadate/domain/member/entity/Member.java
> +@Getter
@ToString 사용하는 것 좋습니다!
연관 관계로 묶여있는 필드를 제외하는 방법이 괜찮아 보이네요.

2024-08-17 11:17 UTC, YongGoose commented on src/test/java/com/fixadate/domain/member/controller/impl/MemberControllerImplTest.java
@JJ503 
변경 완료 했습니다!

2024-08-18 06:40 UTC, JJ503 approved these changes
변경 사항들 모두 확인했습니다!
고생 많으셨습니다~!

2024-08-18 06:41 UTC, merged