adate 테스트 추가 (진행 중)
fixadate/fixadate_backend pull request #199
Opened 2024-08-11 13:56 UTC by JJ503

## 📄 작업 내용 요약

현재 작업 중인 pr입니다.
현재까지 진행 사항은 아래와 같습니다.
- adate 엔티티, 레파지토리 리팩터링 및 테스트 추가
- adate 서비스 리팩터링

## 📎 Issue 번호

- close #190 

## 📌 PR 유형

어떤 변경 사항이 있나요?

- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [x] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [x] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## ✅ PR Checklist

PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2024-08-13 00:33 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/entity/Adate.java
> +	// TODO: [의견] if 대신 is는 어떤가요? api 등 고려해야 할 게 많을까봐 변경은 하지 않았습니다.
is로 변경하는 것이 필드의 역할을 더 직관적으로 보이게 해주는 것 같아 변경하는 것이 좋을 것 같습니다!

2024-08-13 00:33 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/entity/Adate.java
> +	// TODO: [질문] ifAllday는 참조타입이고 reminders는 원시 타입인 이유가 무엇인가요? 구글 캘린더 때문일까요?
참조 타입 / 원시 타입은 null이 가능한지 여부로 나누었습니다!!

저번 회의 때도 비슷한 얘기가 나왔는데 Adate에 기능에 비해 필드가 너무 많다고 생각됩니다.
그래서 이번 리팩토링을 할 때 Adate에서 사용하지 않을 것 같은 필드들을 삭제하는건 어떻게 생각하시는지 궁금합니다.

2024-08-13 00:33 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/entity/Adate.java
> +	//  혹은 deleteTag에서 adate의 removeTagAndColor를 호출하는 것처럼, tag의 색상 update 시 updateTage(tag.color)를 통해 호출하는 건 어떤가 싶습니다.
Tag를 삭제할 때는 Adate와 연관 관계가 있으면 안 돼서 deleteTag는 동기적으로 처리를 했습니다.
하지만, updateTag는 동기적으로 처리를 할 필요가 없어 Spring Event를 통해 처리를 했습니다.

그래서 저는 동기 vs 비동기 관점으로 봐서 처리를 했는데 정수님 의견은 어떠신가요?

2024-08-13 00:33 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/mapper/AdateMapper.java
> +	 * TODO: [질문] 제 경우 private 메서드 순서를 저는 처음 사용한 메서드 바로 아래 둡니다. 혹시 어떻게 정렬하시나요?
좋은 것 같습니다. 이번 리팩토링 부터 반영하도록 하겠습니다.
- 저도 사용한 메서드 아래에 두는 방법으로 하고 있는데 처음 사용한 메서드 아래에 두는 것으로 강제하지는 않았습니다.

2024-08-13 00:33 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/mapper/AdateMapper.java
> +	 *  check 관련 해당 메서드를 사용하는 곳은 adateMapper 뿐이기도 하고요. 그래서 이 클래스로 이동해봤습니다.
제 생각은 약간 다릅니다.
Mapper 클래스는 데이터 변환과 같은 역할을 수행하는데 check는 mapper 클래스의 역할이 아니라서 다른 클래스에 존재하는 것이 유지보수 관점에서 좋을 것 같다고 생각합니다.
- Util도 괜찮을 수 있고 아니면 이번 기회에 Validation 클래스를 생성하는 것도 좋은 방법이 될 수 있겠네요.

정수님의 의견도 편하게 말씀해주세요 :)

2024-08-13 00:33 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/repository/AdateQueryRepository.java
> +	// TODO: [질문] 어떤 용도인가요? 삭제해도 될까요?
넵! 삭제하셔도 됩니다.
예전에 성능테스트를 할 때 복합키 성능을 측정하기 위해 넣었던 메서드인데 삭제하는 것을 까먹었네요;;ㅎㅎ

2024-08-13 00:33 UTC, YongGoose commented on src/main/java/com/fixadate/global/exception/badrequest/RedisRequestException.java
> +	//  클래스명이 동일해 아래와 같이 되는데 어떻게 생각하시나요?
저번 회의때 처리한 안건으로 기억하고 있습니다. 혹시 변경 사항이 있으면 알려주세요

2024-08-13 00:33 UTC, YongGoose commented on src/test/java/com/fixadate/domain/adate/entity/AdateTest.java
> +	// TODO: [질문] 리마인드 여부를 의미하는 게 맞을까요? 맞다면 정확히 어떤 기능인가요?
Adate 필드 값 결정 후, 계속 필요하다고 판단 되면 그 때 자세히 말씀드리겠습니다.

2024-08-13 00:33 UTC, YongGoose commented on src/test/java/com/fixadate/domain/adate/repository/fixture/AdateQueryRepositoryFixture.java
> +		// TODO: [질문] jpa repository를 사용해도 괜찮을까요? 만약, jpa를 사용하지 않게 되면 수정 범위가 여기까지로 확장됩니다.
넵! 사용하셔도 괜찮을 것 같습니다.

2024-08-13 00:33 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/event/handler/AdateHandler.java
> +		//  기존에는 member 정보는 저장하지 않고 있었습니다.
맞습니다! 좋은 지적 감사합니다. 👍🏻

2024-08-13 00:33 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/entity/Adate.java
> +	// TODO: [질문] 구글 캘린더에서 수정이 될 때 ifAllDay, alertWhen, repeatFreq은 수정이 안 되나요?
Adate 필드 값 결정 후, 계속 필요하다고 판단 되면 그 때 자세히 말씀드리겠습니다.

2024-08-15 04:01 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/entity/Adate.java
> +	// TODO: [질문] ifAllday는 참조타입이고 reminders는 원시 타입인 이유가 무엇인가요? 구글 캘린더 때문일까요?
> 참조 타입 / 원시 타입은 null이 가능한지 여부로 나누었습니다!!

이런 이유라면, `AdateResponse`에서도 참조 타입으로 둬야 하는 것이 아닐까 싶습니다.
mapper를 통해 `AdateResponse`로 변환시 npe가 발생할 수도 있기 때문입니다.
그런데, 프론트로 넘겨줄 때 null로 넘겨줘도 괜찮은 것인지, 합의가 된 상황인지 확인차 여쭤보고 수정하고자 합니다!
('Fixadate 연동규격서'에서는 boolean으로 되어 있어서요!)

2024-08-15 04:02 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/entity/Adate.java
> +	// TODO: [질문] ifAllday는 참조타입이고 reminders는 원시 타입인 이유가 무엇인가요? 구글 캘린더 때문일까요?
> 이번 리팩토링을 할 때 Adate에서 사용하지 않을 것 같은 필드들을 삭제하는건 어떻게 생각하시는지 궁금합니다.

사용하지 않는 것은 삭제해야 하는 것이 맞다고 생각합니다!
다만, 이전에 프론트 측과 합의가 없어도 되는 것인지 궁금합니다.

2024-08-15 04:50 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/entity/Adate.java
> +	// TODO: [질문] ifAllday는 참조타입이고 reminders는 원시 타입인 이유가 무엇인가요? 구글 캘린더 때문일까요?
> 프론트 측과 합의가 없어도 되는 것인지 궁금합니다.

아무래도 일방적으로 지우면 프론트 측에 혼란이 올 수 있어 얘기를 해보고 하는 게 나을 것 같습니다!

아니면 1.0.0 이후에 리팩토링을 하는 방향으로 진행 해볼까요...?

2024-08-20 05:35 UTC, YongGoose requested changes
컨벤션으로 코멘트를 남길 부분이 딱히 보이지 않아서 질문에 대한 답변 위주로 코멘트 달았습니다!

고생하셨습니다 👍

2024-08-20 05:35 UTC, YongGoose commented on src/test/java/com/fixadate/domain/adate/repository/fixture/AdateQueryRepositoryFixture.java
EntityManager을 이용해 flush를 하지 않아도 쿼리가 발생 했나요?

2024-08-20 05:35 UTC, YongGoose commented on src/test/java/com/fixadate/domain/adate/service/AdateServiceTest.java
> +		//  일단 통합 테스트를 진행하기로 했기에, 후자로 진행했습니다.
넵 저도 동일하게 생각합니다!

2024-08-20 05:35 UTC, YongGoose commented on src/test/java/com/fixadate/domain/adate/service/AdateServiceTest.java
> +		void 태그가_있는_adate_저장시_태그를_저장하는_이벤트를_한번_호출한다() {
태그를_조회하는_이벤트를 한_번_호출한다가 맞는 메서드 이름일 것 같아요!

2024-08-20 05:35 UTC, YongGoose commented on src/test/java/com/fixadate/domain/adate/service/AdateServiceTest.java
> +		@RepeatedTest(100)
REPEATED_COUNT로 통일을 시키면 깔끔할 것 같습니다.

2024-08-20 05:35 UTC, YongGoose commented on src/test/java/com/fixadate/domain/adate/service/AdateServiceTest.java
> +	class RemoveAdateTest {
일정을 삭제했을 때 Redis에 정상적으로 저장이 됐는지도 확인하면 좋을 것 같습니다.

2024-08-20 05:35 UTC, YongGoose commented on src/test/java/com/fixadate/domain/adate/service/AdateServiceTest.java
ServiceTest는 아직 작업 중이신 것 같아서 깊게 확인하지는 않았습니다!

개인적으로 엣지 케이스를 활용한 테스트가 추가 되었으면 좋겠다고 생각합니다.
-  adate를 16일 12시 - 17일 12시로 저장을 했는데 조회할 때 startTime이 17일 12시면 조회가 되나요?
-  adate를 16일 12시 - 18일 12시로 저장을 했는데 조회를 17시 00시부터 19일 00시로 조회를 하면 조회가 되나요?

2024-08-20 05:35 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/event/handler/AdateHandler.java
>   */
삭제 부탁드릴게요..! 😅

2024-08-29 14:58 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/controller/impl/AdateControllerImpl.java
> +		final AdateUpdateDto adateUpdateDto = AdateMapper.toDto(adateUpdateRequest);
나중에 mapper가 많이 생기게 된다면 static import를 헀을 경우 헷갈리지 않을까요?
그래서 메서드 네이밍을 AdateMapper가 붙어있을 경우 이해하기 쉽도록 만들기도 헀습니다.
해당 클래스 내에 있는 메서드기에 Adate와 관련해 한 번 더 붙이는 것도 중복되는 느낌이 있기도 했고요!
혹시 어떻게 생각하시는 지 궁금합니다!

2024-08-29 14:59 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/controller/impl/AdateControllerImpl.java
> +	// TODO: [질문] requestParam에 기본 값이 없어도 괜찮을까요? 혹은 requestParam이 필수 등의 옵션 설정이 필요 없을까요? (다른 메서드들도)
필수라서 괜찮을 것 같긴하네요!

2024-08-29 15:01 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/entity/Adate.java
> +	// TODO: [질문] ifAllday는 참조타입이고 reminders는 원시 타입인 이유가 무엇인가요? 구글 캘린더 때문일까요?
좋습니다!
우선 이번 pr에서는 현재 형식을 유지하고 이후에 리팩터링을 진행하는 것으로 하겠습니다.

2024-08-29 15:02 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/entity/Adate.java
> +	// TODO: [의견] if 대신 is는 어떤가요? api 등 고려해야 할 게 많을까봐 변경은 하지 않았습니다.
v1 배포 이후에 진행하는 것으로 하겠습니다!

2024-08-29 15:06 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/entity/Adate.java
> +	//  혹은 deleteTag에서 adate의 removeTagAndColor를 호출하는 것처럼, tag의 색상 update 시 updateTage(tag.color)를 통해 호출하는 건 어떤가 싶습니다.
동기, 비동기 방식은 현재 좋다고 생각합니다.
제가 질문드린 것은 기존 해당 메서드의 네이밍이 어떤 동작을 할지 유추하기 어렵다는 이야기였습니다.
그래서 현재 메서드명(`refreshColorFromCurrentTag`)으로 수정해보았고 그럼에도 보기 어렵다면 `updateTag(tag.color)`를 공통적으로 사용하자는 이야기였습니다.

2024-08-29 15:08 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/mapper/AdateMapper.java
> +@NoArgsConstructor(access = AccessLevel.PRIVATE)
서로 어떤 점이 다른 것인지 궁금합니다!

2024-08-29 15:12 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/mapper/AdateMapper.java
> +	public static AdateRegisterDto toDto(final AdateRegisterRequest request) {
네이밍의 규칙을 이야기해보면 좋을 것 같습니다.
사실 저는 파라미터와 응답값으로 유추가 가능할 것이라 생각했으며, 매개변수가 `AdateRegisterRequest`의 응답값은 당연히 `AdateRegisterDto`지 않을까 생각했습니다.
그래서 사실 오히려 아래 메서드들의 네이밍도 변경하고 싶다고 생각했습니다.
하지만, 이건 제 개인적인 의견이기에 제 의견을 들은 후의 용준님의 의견이 궁금합니다!

2024-08-29 15:15 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/mapper/AdateMapper.java
> +	 *  check 관련 해당 메서드를 사용하는 곳은 adateMapper 뿐이기도 하고요. 그래서 이 클래스로 이동해봤습니다.
그렇다면 아예 `TimeUtil`을 상속받은 `EventTimeUtil`을 만드는 것에 대해 어떻게 생각하시나요?

2024-08-29 15:17 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/repository/AdateQueryRepository.java
> +	public List<Adate> findByDateRange(
이 이야기를 회의 때 한번 했던 것으로 기억하는데 결론을 기억 하실까요..? 😅

2024-08-29 15:18 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/service/repository/AdateRepository.java
수정 완료했습니다!

2024-08-29 15:19 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	private static final int ADATE_REDIS_DURATION = 20;
좋습니다.
개인적으로 상수 enum에 대해 궁금했던 점은 오로지 한 클래스에서만 사용되고 재사용되지 않는 상수에 대해서도 enum에 둬야 할 이유가 있는지 궁금했습니다!

2024-08-29 15:25 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	// TODO: [질문] Event라는 네이밍은 TagSettingEvent의 Event인지 다른 의미가 있는 것인지 궁금합니다.
혹은 현재 구글만 있기에 구글 캘린더로 하드코딩 되어 있지만, 외부 캘린더를 저장하는 메서드가 될 수 있을 것이라 생각해 `registerExternalCalendar` 같은 이름은 어떨까요?
또한, `GOOGLE_CALENDAR.getValue()`를 하드코딩하는 게 아니라 메서드 호출 시 매개변수로 받는 것이 더 적절하다고 생각하기도 합니다.

추가로 구글 캘린더 외의 다른 캘린더 들에서도 자신들의 일정을 `Event`라고 표현할까요?
만약 아니라면, 구글 캘린더와 관련된 로직 외에서는 `Event`라는 네이밍 사용을 않는 것이 적절하지 않을까 싶어 질문드립니다.

2024-08-29 15:26 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	// TODO: [질문] 회원정보를 받아, 해당 회원의 일정인지 확인은 필요 없을까요?
해당 방식 적용 이후 이 부분도 리팩터링 하는 방식으로 진행하겠습니다!

2024-08-29 15:29 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	//  여기서 검증한다면, TimeUtil의 유효성을 검증하는 느낌인데, 오히려 클라이언트에서 전달 받은 값을 검증하는 게 적절하지 않을까 생각합니다.
말이 조금 잘못 전달된 것 같습니다...!
제가 말씀드린 것은 startTime과 endTime인 검증할 필요가 없으며, 서비스에서 year와 month에 대한 검증이 필요하단 의미였습니다.
컨트롤러에서 검증하는 것이 적절하다고 생각하신 이유가 궁금합니다!

2024-08-29 15:30 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	// TODO: [질문] 해당 메서드에서는 checkStartAndEndTime을 확인하지 않는 이유가 있을까요?
개인적으로 하기와 동일하지 않다고 생각했습니다.
아래 메서드의 경우는 year와 month만 받고 시작일과 종료일을 로직상에서 직접 설정해주기에 검증이 필요없고 잘못되었다면 입력이 아닌 로직 자체가 틀린 것이라 생각합니다.
하지만, 현재 메서드의 경우 시작일과 종료일 자체를 사용자에게 받아오고 있습니다. 그렇기에 여기서는 검증이 꼭 필요하다고 생각했습니다.

2024-08-29 15:32 UTC, JJ503 commented on src/test/java/com/fixadate/domain/adate/entity/AdateTest.java
> +	void 일정의_주인이라면_거짓을_반환한다() {
수정했습니다!

2024-08-29 15:37 UTC, JJ503 commented on src/test/java/com/fixadate/domain/adate/service/AdateServiceTest.java
> +	class RemoveAdateTest {
해당 로직상에는 redis와 관련된 로직이 없는데, 자동으로 삭제가 되는 것일까요?

2024-08-29 15:38 UTC, JJ503 commented on src/test/java/com/fixadate/domain/adate/service/AdateServiceTest.java
> +	class RemoveAdateTest {
앗 이 메서드가 아니라 아래 메서드를 말씀하시는거겠죠?

2024-08-29 15:39 UTC, JJ503 commented on src/test/java/com/fixadate/domain/adate/service/AdateServiceTest.java
> +	class RemoveAdateTest {
`RemoveAdateByCalendarIdTest`가 redis 로직이 있는 메서드라 해당 메서드에 검증 추가했습니다.

2024-08-29 16:00 UTC, JJ503 commented on src/test/java/com/fixadate/domain/adate/service/AdateServiceTest.java
https://github.com/fixadate/fixadate_backend/pull/199#discussion_r1736505183
해당 코멘트 답변 주신 후 작업 진행하도록 하겠습니다.

2024-08-31 05:38 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/controller/impl/AdateControllerImpl.java
> +		final AdateUpdateDto adateUpdateDto = AdateMapper.toDto(adateUpdateRequest);
mapper가 많이 있는 경우 헷갈릴수도 있겠네요,,
`AdateMapper.toDto` 말고 차라리 public API 네이밍을 조금 더 명확하게 하는 것은 어떨까요?
ex) `toRequestDto`

만약 이 방법도 별로라면 mapper을 static import 하지 않도록 하겠습니다!
(저의 경우 static import를 해서 통일이 필요할 것 같네요)

2024-08-31 05:40 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/mapper/AdateMapper.java
> +@NoArgsConstructor(access = AccessLevel.PRIVATE)
두 방식의 차이점은 없습니다!

다만 private 생성자를 조금 더 명확하게 볼 수 있게 하려고 사용 했습니다.
> Lombok의 경우 너무 편한 어노테이션이 많아서 가끔씩은 pojo가 아닌 Lombok을 사용하는 것이 편할 때도 있는 것 같습니다ㅎㅎ

만약 Lombok을 그대로 사용해도 괜찮을 것 같다고 판단되면 변경하지 않으셔도 됩니다.

2024-08-31 05:47 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/mapper/AdateMapper.java
> +	public static AdateRegisterDto toDto(final AdateRegisterRequest request) {
- https://github.com/fixadate/fixadate_backend/pull/199#discussion_r1736414087
이 코멘트의 연장선인 것 같습니다.

하기의 링크에 따르면 해당 객체를 다른 형태의 객체로 변환해주는 메서드 명에서 to를 사용한다고 합니다.
그래서 `AdateRegisterDto`로 변환하는 메서드는 `toRegisterDto`로 메서드 이름을 지었던 것입니다.

개인적으로 정수님의 의견도 너무 깔끔하고 좋을 것 같지만 무슨 작업을 하는지(어떤 dto로 변경하는지)가 뚜렷한 것도 좋을 것 같네요.
- https://tecoble.techcourse.co.kr/post/2020-04-26-Method-Naming/
![image](https://github.com/user-attachments/assets/d2a4886e-90bf-4bec-8d34-0fb6612ac1ea)

2024-08-31 05:48 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/repository/AdateQueryRepository.java
> +	public List<Adate> findByDateRange(
@Transactional(readonly=true)를 남겨놓고 setHint를 삭제하기로 결론이 났습니다!

2024-08-31 05:51 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	// TODO: [질문] Event라는 네이밍은 TagSettingEvent의 Event인지 다른 의미가 있는 것인지 궁금합니다.
우선 `registerExternalCalendar` 메서드 이름은 좋은 의견인 것 같습니다!

Event는 구글 캘린더에서만 사용할 지 다른 캘린더에서도 사용할 지 아직 생각해보지 않았습니다...ㅎㅎ
좋은 의견 부탁드려요 :)

Google 관련 로직들은 우선 정수님의 방법대로 리팩토링을 진행한 뒤, 제가 피드백을 주는 방식으로 진행하는 것 어떨까요?

2024-08-31 05:53 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	// TODO: [질문] 여기서 week는 한주차라는 의미가 아닌걸까요? 시간만 없을 뿐 getAdateByStartAndEndTime와 다른점을 잘 모르겠습니다.
음... LocalDateTime과 시간을 필터링 하는 것에 대해 조금 더 자세히 설명 부탁드려도 될까요?

2024-08-31 06:01 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	//  여기서 검증한다면, TimeUtil의 유효성을 검증하는 느낌인데, 오히려 클라이언트에서 전달 받은 값을 검증하는 게 적절하지 않을까 생각합니다.
앗, 제가 코드를 잘못 본 것 같네요.
하기의 코드에서는 startTime, endTime을 검증할 필요가 없습니다.
정수님의 말씀대로 year, month에 대해 테스트를 하는 것이 맞는 것 같네요.

ex) month가 1 ~ 12사이의 값인지

2024-08-31 06:05 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	// TODO: [질문] 해당 메서드에서는 checkStartAndEndTime을 확인하지 않는 이유가 있을까요?
넵 맞습니다.
하기의 메서드의 경우 멤버로부터 시간을 받기 때문에 검증을 꼭 해야 할 것 같네요.

다만 한 가지 얘기해보고 싶은 점이 있다면, 검증을 Controller 레이어에서 할 지, Service 레이어에서 할 지 얘기해보면 좋을 것 같습니다.

Controller 레이어에서 하면 개인적으로 Service 레이어까지 가기 전에 검증을 할 수 있어서 좋은 것 같습니다. 
그리고 개인적으로 입력값 검증은 굳이 service 레이어까지 가서 해야 할까..? 라는 생각도 드네요

2024-08-31 06:07 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/mapper/AdateMapper.java
> +	 *  check 관련 해당 메서드를 사용하는 곳은 adateMapper 뿐이기도 하고요. 그래서 이 클래스로 이동해봤습니다.
좋은 것 같습니다 👍

2024-08-31 06:09 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/entity/Adate.java
> +	//  혹은 deleteTag에서 adate의 removeTagAndColor를 호출하는 것처럼, tag의 색상 update 시 updateTage(tag.color)를 통해 호출하는 건 어떤가 싶습니다.
`refreshColorFromCurrentTag`으로도 괜찮은 것 같습니다.

2024-09-01 04:53 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/controller/impl/AdateControllerImpl.java
> +		final AdateUpdateDto adateUpdateDto = AdateMapper.toDto(adateUpdateRequest);
`toRequestDto` 네이밍 좋습니다! dto에도 여러가지 형식이 있을테니 좀 더 명확해지겠네요!

2024-09-01 04:55 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/controller/impl/AdateControllerImpl.java
> +		final AdateUpdateDto adateUpdateDto = AdateMapper.toDto(adateUpdateRequest);
dto가 아닌 좀 더 명확한 dto로서의 역할을 네이밍에 넣어주는 것은 좋습니다!
그런데 request dto를 dto로서 사용하는 것인데 해당 네이밍에 있어 이해가 괜찮은지 궁금합니다.
해당 메서드는 `AdateRegisterRequest`를 `AdateRegisterDto`로 변환하는 것이기에 확인차 질문드립니다.

2024-09-01 04:56 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/mapper/AdateMapper.java
> +@NoArgsConstructor(access = AccessLevel.PRIVATE)
그렇군요!
Lombok 라이브러리를 사용하고 있었기에 상관 없다고 생각했습니다.
그런데 해당 이유라면 저도 동일한 방식으로 수정하도록 하겠습니다!

2024-09-01 05:01 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/mapper/AdateMapper.java
> +	public static AdateRegisterDto toDto(final AdateRegisterRequest request) {
처음에는 `toRegisterDto`로 짓게 된다면, 해당 dto 클래스 명이 변경될 때마다 메서드도 변경해야 한다는 불편함이 있지 않을까 생각했습니다. 해당 메서드의 역할은 어떤 형식인지와 상관없이 그저 `AdateRegisterRequest`를 dto로만 변환해 주는 역할이라고 생각했기 때문입니다.

그런데, 용준님의 의견을 보고 고민해 본 결과 위 상황은 메서드의 역할이 바뀐 것이므로 메서드 명을 변경해 주는 것이 자연스럽겠네요! 오히려 `AdateRegisterRequest`를 또 다른 형식의 dto 객체로 변환하는 상황이 발생했을 때 현재 제 방식이라면 메서드 명과 매개변수가 동일하기에 문제가 발생할 수도 있고요!
그래서 용준님 의견이 더 맞는 것 같습니다. 해당 방식으로 수정하도록 하겠습니다!

2024-09-01 05:02 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/controller/impl/AdateControllerImpl.java
> +		final AdateUpdateDto adateUpdateDto = AdateMapper.toDto(adateUpdateRequest);
https://github.com/fixadate/fixadate_backend/pull/199#discussion_r1739974455
메서드 네이밍에 대한 추가적인 의견 해당 코멘트에 달아두었습니다!

2024-09-01 05:04 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/mapper/AdateMapper.java
> +	public static AdateRegisterDto toDto(final AdateRegisterRequest request) {
그런데 고민인 부분은 아래와 같습니다.
기존 mapper의 메서드 형식은 `{변경할 객체 타입}To{변경될 객체 타입}`이었습니다.
해당 방식과 `to{변경될 객체 타입}` 중 어떤 방식이 혹시 더 이해하기 쉬우실까요?

2024-09-01 05:05 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	private static final int ADATE_REDIS_DURATION = 20;
의견 주시면 감사하겠습니다!

2024-09-01 05:17 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	// TODO: [질문] 여기서 week는 한주차라는 의미가 아닌걸까요? 시간만 없을 뿐 getAdateByStartAndEndTime와 다른점을 잘 모르겠습니다.
캘린더에서 필터링을 진행할 때 보통은 날짜 단위가 최소 단위인 것 같아 질문드렸습니다.
그래서 LocalDateTime과 LocalDate 포맷 각각을 통해 수행하는 역할이 궁금했습니다!

2024-09-01 11:56 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/mapper/AdateMapper.java
> +	public static AdateRegisterDto toDto(final AdateRegisterRequest request) {
`to{변경될 객체 타입}` 방식이 더 이해하기 쉬울 것 같습니다!

2024-09-01 11:59 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	// TODO: [질문] 여기서 week는 한주차라는 의미가 아닌걸까요? 시간만 없을 뿐 getAdateByStartAndEndTime와 다른점을 잘 모르겠습니다.
`LocalDateTime`, `LocalDate`, `year & month` 전부 다 같은 역할을 수행합니다 (캘린더 조회)
다만 기획에 따라 다양한 조회를 할 수 있기에 여러가지 선택지를 미리 준비 해놓은 것입니다!

ex) 시간 단위 조회, 날짜 조회, 월 조회

2024-09-01 12:02 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	private static final int ADATE_REDIS_DURATION = 20;
하나의 클래스에서만 사용되는 상수는 그 클래스에 정의하고 재사용되는 상수에 대해서만 enum으로 관리하는 것도 좋은 방법인 것 같네요.

상수 관리 같은 것은 규칙을 정해야 할 것 같은데 하기의 방법으로 하는 거 괜찮으실까요?
> 하나의 클래스에서만 사용되는 상수는 그 클래스에 정의하고 재사용되는 상수에 대해서만 enum으로 관리하는 것도 좋은 방법인 것 같네요.

2024-09-01 12:08 UTC, YongGoose commented on src/main/java/com/fixadate/domain/auth/service/AuthService.java
> +		// TODO: [질문]  TagMemeberSettingEvent()의 경우 무조건 적으로 태그를 GOOGLE로 수행하는데 이유가 있을까요?
Google 태그는 Member가 회원가입을 할 때 기본적으로 생성되는 태그입니다!
그래서 회원가입을 할 때 이벤트를 발신하고 핸들러에서 이벤트를 수신한 뒤, 구글 태그를 생성 / 저장하는 것입니다.

Google Calendar에서 이벤트를 가져올 때 Google 태그로 지정이 되게 하기 위해 설정 해놓은 것입니다!

ps. 그 외 Tag가 저장되는 이벤트가 언제 실행될 지 생각해보는 것도 좋을 것 같네요. (다양한 의견 기대하겠습니다 ㅎㅎ)
ex) 회원 가입이 완료된 뒤 (transaction commit 이후) / 이전 or 동기 / 비동기

2024-09-02 00:19 UTC, JJ503 commented on src/main/java/com/fixadate/domain/auth/service/AuthService.java
> +		// TODO: [질문]  TagMemeberSettingEvent()의 경우 무조건 적으로 태그를 GOOGLE로 수행하는데 이유가 있을까요?
질문을 좀 더 설명드리자면 다음과 같습니다.
현재 저희 서비스에서 구글 로그인만 있는 것이 아니기에, 다른 방식으로 로그인한 사람에게도 구글 태그를 부여해 주나요?
그렇다면 다른 방식으로 로그인한 사용자는 어떻게 구글 캘린더와 연결할 수 있을까요?
또한, 이후에 다른 캘린더로도 확장되었을 때 모든 캘린더에 대한 태그를 생성하는 것인지 역시 궁금했습니다.

2024-09-02 00:20 UTC, JJ503 commented on src/main/java/com/fixadate/domain/auth/service/AuthService.java
> +		// TODO: [질문]  TagMemeberSettingEvent()의 경우 무조건 적으로 태그를 GOOGLE로 수행하는데 이유가 있을까요?
제가 질문을 모호하게 작성한 것 같네요..!
질문을 좀 더 설명드리자면 다음과 같습니다.
현재 저희 서비스에서 구글 로그인만 있는 것이 아니기에, 다른 방식으로 로그인한 사람에게도 구글 태그를 부여해 주나요?
그렇다면 다른 방식으로 로그인한 사용자는 어떻게 구글 캘린더와 연결할 수 있을까요?
또한, 이후에 다른 캘린더로도 확장되었을 때 모든 캘린더에 대한 태그를 생성하는 것인지 역시 궁금했습니다.

2024-09-03 13:21 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	// TODO: [질문] Event라는 네이밍은 TagSettingEvent의 Event인지 다른 의미가 있는 것인지 궁금합니다.
Event의 경우 google api 라이브러리에서 만들어진 타입 아닌가요?
다른 캘린더에서도 사용할 수 있는 것일까요?

2024-09-03 14:36 UTC, JJ503 commented on src/main/java/com/fixadate/domain/auth/service/AuthService.java
> +		// TODO: [질문]  TagMemeberSettingEvent()의 경우 무조건 적으로 태그를 GOOGLE로 수행하는데 이유가 있을까요?
카톡으로 이야기한 대로 구글 캘린더 외의 외부 캘린더도 쉽게 적용할 수 있도록 확장해 보았습니다.
다만, Event 타입을 사용함에 있어 해당 타입은 Google api의 라이브러리를 통해 만들어진 타입이기에 다른 캘린더에서는 적용이 어렵지 않을까 싶습니다.
그런데 아직 다른 캘린더에 대해서는 잘 알지 못해 확인이 필요하기에 일단 이번 pr에서는 넘어가려 합니다!

2024-09-03 14:39 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	// TODO: [질문] Event라는 네이밍은 TagSettingEvent의 Event인지 다른 의미가 있는 것인지 궁금합니다.
일단 메서드에서는 Event라는 네이밍을 최대한 지양하도록 리팩터링 해보았습니다.

2024-09-03 15:50 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	// TODO: [질문] 해당 메서드에서는 checkStartAndEndTime을 확인하지 않는 이유가 있을까요?
검증 로직 추가했습니다.
컨트롤러에서도 검증해주지만, 서비스 레이어에서도 2차 검증이 필요하다고 생각해 결론적으로는 컨트롤러와 서비스에서 모두 검증하도록 했습니다.
이 부분에 대해 어떻게 생각하실까요?

2024-09-03 15:54 UTC, JJ503 commented on src/test/java/com/fixadate/domain/adate/service/AdateServiceTest.java
그런데 해당 테스트를 진행하려면 아예 set을 통해 시간을 고정해 두는 것이 좋을까요?
현재도 그러긴 했지만, 100번 테스트를 하는 것이 의미가 있는지 궁금합니다!

2024-09-04 00:16 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	// TODO: [질문] Event라는 네이밍은 TagSettingEvent의 Event인지 다른 의미가 있는 것인지 궁금합니다.
> Event의 경우 google api 라이브러리에서 만들어진 타입 아닌가요?

Event의 경우 Google api 라이브러리에서만 사용할 수 있게 만들어진 클래스입니다!

> 일단 메서드에서는 Event라는 네이밍을 최대한 지양하도록 리팩터링 해보았습니다.

넵! 좋은 방법인 것 같습니다.

2024-09-04 00:38 UTC, YongGoose requested changes

2024-09-04 00:38 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	// TODO: [질문] 해당 메서드에서는 checkStartAndEndTime을 확인하지 않는 이유가 있을까요?
`final` 키워드가 있어 `Controller`에서 검증을 하면 `Service`에서 할 필요가 없다고 생각하긴 합니다.

하지만 `getAdateByStartAndEndTime` 메서드의 경우 다른 조회 방식 (`getAdatesByMonth`, `getAdatesByDate`) 에서도 사용하는 메서드이기에 검증이 필요할 것 같긴 하네요.

결과적으로는 `getAdateByStartAndEndTime`에서는 컨트롤러, 서비스 레이어 둘 다 검증이 필요하다고 정수님과 동일하게 생각합니다!
하지만, `getAdateByStartAndEndTime` 메서드가 service에서 재사용되지 않았다면 검증이 필요 없을 것 같다고 생각합니다.
> final 키워드를 통해 재할당이 불가하기에 똑같은 값을 두 번 검증한다는 느낌이 드네요.

2024-09-04 00:38 UTC, YongGoose commented on src/test/java/com/fixadate/domain/adate/service/AdateServiceTest.java
> set을 통해 시간을 고정해 두는 것이 좋을까요?

이 부분은 `Fixture Monkey` 기여가 끝난 뒤 제가 리팩토링을 진행하도록 하겠습니다!
미리 설명을 드리자면, `register`한 연산을 이름과 함께 등록을 해서 (시작, 종료, 존재하지 않는 일정 시작, 존재하지 않는 일정 종료) arbitraryBuilder에서 선택할 수 있도록 구현할 계획입니다!

그리고 이때 `register`한 연산은 `set`을 통해 값을 고정시키는 것이 아니라 `between` 등 값을 다양하게 받을 수 있는 함수를 사용하려고 합니다! 
> 나중에 구현을 할 때 Issue에서 더 자세히 말씀 드리겠습니다!

---
> 100번 테스트를 하는 것이 의미가 있는지 궁금합니다!

현재의 경우 100번 테스트를 하는 것이 의미는 없을 것 같네요..
한 번만 진행하셔도 될 것 같습니다!

2024-09-04 00:40 UTC, YongGoose commented on src/test/java/com/fixadate/domain/adate/service/AdateServiceTest.java
> set을 통해 시간을 고정해 두는 것이 좋을까요?

이 부분은 `Fixture Monkey` 기여가 끝난 뒤 제가 리팩토링을 진행하도록 하겠습니다!
미리 설명을 드리자면, `register`한 연산을 이름과 함께 등록을 해서 (시작, 종료, 존재하지 않는 일정 시작, 존재하지 않는 일정 종료) `arbitraryBuilder`에서 선택할 수 있도록 구현할 계획입니다!

그리고 이때 `register`한 연산은 `set`을 통해 값을 고정시키는 것이 아니라 `between` 등 값을 다양하게 받을 수 있는 함수를 사용하려고 합니다!

나중에 구현을 할 때 Issue에서 더 자세히 말씀 드리겠습니다!

---

> 100번 테스트를 하는 것이 의미가 있는지 궁금합니다!

현재의 경우 100번 테스트를 하는 것이 의미는 없을 것 같네요..
한 번만 진행하셔도 될 것 같습니다!

2024-09-04 00:42 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	// TODO: [질문] 해당 메서드에서는 checkStartAndEndTime을 확인하지 않는 이유가 있을까요?
`final` 키워드가 있어 `Controller`에서 검증을 하면 `Service`에서 할 필요가 없다고 생각하긴 합니다.

하지만 `getAdateByStartAndEndTime` 메서드의 경우 다른 조회 방식 (`getAdatesByMonth`, `getAdatesByDate`) 에서도 사용하는 메서드이기에 검증이 필요할 것 같긴 하네요.

결과적으로는 `getAdateByStartAndEndTime`에서는 컨트롤러, 서비스 레이어 둘 다 검증이 필요하다고 정수님과 동일하게 생각합니다!
하지만, `getAdateByStartAndEndTime` 메서드가 service에서 재사용되지 않았다면 검증이 필요 없을 것 같다고 생각합니다.
> final 키워드를 통해 재할당이 불가하기에 똑같은 값을 두 번 검증한다는 느낌이 드네요.

2024-09-04 01:28 UTC, YongGoose commented on src/main/java/com/fixadate/domain/googlecalendar/service/GoogleService.java
>  		events.parallelStream().forEach(event ->
제가 작성한 코드이긴 하지만.. 병렬 처리를 제외하는 것이 좋을 것 같습니다.

이미 @Async를 통해 비동기로 작동을 하고 있는데 여기에서 병렬 처리까지 하게 되면 예상치 못하게 스레드를 많이 사용하는 경우가 발생할 것 같네요.

2024-09-04 01:28 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/mapper/AdateMapper.java
> +					.color(event.getColorId())
`Adate`의 `color`는 `event`의 `color`가 아닌 `Tag`의 `color`로 설정하기 때문에 해당 코드는 지워야 할 것 같습니다.

2024-09-04 01:28 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/entity/Adate.java
> +	// TODO: [추후] 구글 캘린더에서 수정이 될 때 ifAllDay, alertWhen, repeatFreq은 수정이 안 되나요? -> 답변 필요
`ifAllDay`는 수정이 됩니다.  그 회 `alertWhen`, `repeatFreq`는 수정이 안 됩니다.

하기의 코드를 보면 `ifAllDay`는 `event`에 `start`라는 값이 존재하는지 여부에 따라 판단합니다.
해당 코드를 참고해 ifAllDay 수정로직을 추가하면 될 것 같습니다.

> event에 start가 없는 경우 종일 이벤트이므로 ifAllDay -> true

```java
.ifAllDay(checkEventIsAllDayType(event.getStart()))
```

2024-09-04 01:28 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/entity/Adate.java
> +	public void
개행이 되면 안 되는 곳에서 된 것 같습니다... 😥

2024-09-04 01:28 UTC, YongGoose commented on src/test/java/com/fixadate/domain/adate/entity/AdateTest.java
> +	// TODO: [추후] 리마인드 여부를 의미하는 게 맞을까요? 맞다면 정확히 어떤 기능인가요? -> 답변 필요
하기의 링크를 보면 `Reminder`은 일정이 시작되기 전에 지정된 시간에 실행되는 알람이라고 합니다.
`Fixadate`에서는 `alertWhen`이라는 필드로 알람을 나타내는 것이 있어 해당 필드를 삭제해도 될 것 같습니다.

> 제가 해당 기능을 잘 알아보지 않고 추가 했네요...
> 일단 남겨놓고 1.0.0 이후 Adate Entity 리팩토링에서 제거하셔도 됩니다!

https://developers.google.com/calendar/api/concepts/reminders?hl=ko

2024-09-04 01:28 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/event/object/ExternalCalendarSettingEvent.java
> +// TODO: [추후] Event는 Google 라이브러리 타입이므로, 다른 캘린더로 확장할 수 있도록 리팩터링 필요
Effective Java 3판 아이템 5를 참고하셔서 리팩토링 하셔도 좋을 것 같습니다.

2024-09-04 01:28 UTC, YongGoose commented on src/main/java/com/fixadate/global/exception/ControllerAdvice.java
> +	// TODO: [질문] validate 등 예외가 발생헀을 때에 대해서인데 code를 자체적인 번호로 부여해줘야 할까요?
`MethodArgumentNotValidException`의 경우 spring이 던지는 예외이기 때문에 개발자가 던자는 예외와 code 구분을 두면 좋을 것 같네요.

개인적으로 마이너스(-)를 통해 표현을 하면 어떨까 합니다.
> ex) -1, -2

2024-09-05 00:55 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	// TODO: [질문] 해당 메서드에서는 checkStartAndEndTime을 확인하지 않는 이유가 있을까요?
그렇기도 하고 해당 메서드가 컨트롤러가 아닌 다른 곳에서 사용될 때를 생각했습니다.
필터링 조건이 startTime이 endTime보다 빨라야 한다는 하나의 비즈니스 로직이 아닌가 생각했거든요!

2024-09-05 00:58 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/service/AdateService.java
> +	private static final int ADATE_REDIS_DURATION = 20;
네 확인했습니다.
다만, 캘린더 정보와 같이 묶여야 하는 정보들은 따로 관리해주는 것이 좋다고 생각합니다.
그래서 현재의 상태가 되기도 했고요!
추후 `ExternalCalendar`에 다른 외부 캘린더 정보가 추가되면 될 것이라 생각했습니다.

2024-09-05 00:59 UTC, JJ503 commented on src/test/java/com/fixadate/domain/adate/service/AdateServiceTest.java
그렇다면 현재 테스트는 그대로 유지하면 되는 것이 맞을까요?

2024-09-05 01:01 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/controller/impl/AdateControllerImpl.java
> +		// TODO: [질문] service에서 save한 member 객체로 응답값을 만들어 반환하는 것이 더 적절할까요?
현재 로직을 살펴보면 adateRequest를 통해 반환값을 만들어주고 있음을 확인하실 수 있습니다.
해당 부분은 request 정보가 아닌, 실제로 Service 레이어에서 저장된 회원을 반환해 응답값을 만드는 것이 좋을지에 대한 질문이었습니다!

2024-09-05 01:03 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/dto/response/AdateResponse.java
> +// TODO: [질문] AdateDto까지는 Boolean으로 null이 가능하기에 npe 가능성이 있습니다. 괜찮을까요?
그런 것이라면 다른 곳에서도 `ifAllDay`의 경우 원시타입으로 변경하도록 하겠습니다.
not null도 추가하도록 하겠습니다.

2024-09-05 01:08 UTC, JJ503 commented on src/main/java/com/fixadate/domain/googlecalendar/service/GoogleService.java
>  		events.parallelStream().forEach(event ->
해당 부분은 추후 GoogleCalendar 쪽 리팩터링 때 진행하는 것이 어떨까요?
Adate 외의 부분을 리팩터링 하게 된다면 이후 리팩터링 때 헷갈릴 것 같아 Adate 리팩터링으로 영향이 가는 부분 외에는 진행하지 않았습니다.

2024-09-05 01:16 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/entity/Adate.java
> +	// TODO: [추후] 구글 캘린더에서 수정이 될 때 ifAllDay, alertWhen, repeatFreq은 수정이 안 되나요? -> 답변 필요
확인했습니다.
기존 로직에 없었기에 의도였는지에 대한 질문이었습니다!
그런데, alertWhen과 repeatFreq는 왜 수정이 안 되는 것일까요?

2024-09-05 01:18 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/mapper/AdateMapper.java
> +					.color(event.getColorId())
해당 로직은 기존 로직과 동일하게 진행한 것인데 그렇다면 event와 관련한 color는 모두 변경하면 되는 것일까요?
혹은 해당 부분만 수정하면 되는 것일까요?

``` java
public static Adate eventToEntity(Event event) {
		return builder()
			.title(event.getSummary())
			.notes(event.getDescription())
			.location(event.getLocation())
			.color(event.getColorId())
			.startsWhen(checkStartDateTimeIsNull(event))
			.endsWhen(checkEndDateTimeIsNull(event))
			.ifAllDay(checkEventIsAllDayType(event))
			.calendarId(event.getId())
			.etag(event.getEtag())
			.reminders(event.getReminders().getUseDefault())
			.build();
}
```

2024-09-05 01:20 UTC, JJ503 commented on src/test/java/com/fixadate/domain/adate/entity/AdateTest.java
> +	// TODO: [추후] 리마인드 여부를 의미하는 게 맞을까요? 맞다면 정확히 어떤 기능인가요? -> 답변 필요
이번 PR에서는 일단 넘어가도록 하겠습니다!

2024-09-05 01:21 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/event/object/ExternalCalendarSettingEvent.java
> +// TODO: [추후] Event는 Google 라이브러리 타입이므로, 다른 캘린더로 확장할 수 있도록 리팩터링 필요
해당 부분은 추후 다른 외부 캘린더의 형식을 살펴보고 리팩터링을 진행할 예정으로 이번 PR에서는 넘어가도록 하겠습니다.

2024-09-05 01:21 UTC, JJ503 commented on src/test/java/com/fixadate/domain/adate/entity/AdateTest.java
> +	// TODO: [추후] 리마인드 여부를 의미하는 게 맞을까요? 맞다면 정확히 어떤 기능인가요? -> 답변 필요
이번 PR에서는 일단 넘어가도록 하겠습니다!

2024-09-05 01:21 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/event/object/ExternalCalendarSettingEvent.java
> +// TODO: [추후] Event는 Google 라이브러리 타입이므로, 다른 캘린더로 확장할 수 있도록 리팩터링 필요
해당 부분은 추후 다른 외부 캘린더의 형식을 살펴보고 리팩터링을 진행할 예정으로 이번 PR에서는 넘어가도록 하겠습니다.

2024-09-05 01:22 UTC, JJ503 commented on src/main/java/com/fixadate/global/exception/ControllerAdvice.java
> +	// TODO: [질문] validate 등 예외가 발생헀을 때에 대해서인데 code를 자체적인 번호로 부여해줘야 할까요?
마이너스는 어떤 의미일까요?

2024-09-05 01:23 UTC, JJ503 commented on src/test/java/com/fixadate/domain/adate/entity/AdateTest.java
> +	// TODO: [추후] 리마인드 여부를 의미하는 게 맞을까요? 맞다면 정확히 어떤 기능인가요? -> 답변 필요
이번 PR에서는 일단 넘어가도록 하겠습니다!

2024-09-05 01:23 UTC, JJ503 commented on src/main/java/com/fixadate/global/exception/ControllerAdvice.java
> +	// TODO: [질문] validate 등 예외가 발생헀을 때에 대해서인데 code를 자체적인 번호로 부여해줘야 할까요?
마이너스는 어떤 의미일까요?

2024-09-05 01:23 UTC, JJ503 commented on src/test/java/com/fixadate/domain/adate/entity/AdateTest.java
> +	// TODO: [추후] 리마인드 여부를 의미하는 게 맞을까요? 맞다면 정확히 어떤 기능인가요? -> 답변 필요
이번 PR에서는 일단 넘어가도록 하겠습니다!

2024-09-05 01:23 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/event/object/ExternalCalendarSettingEvent.java
> +// TODO: [추후] Event는 Google 라이브러리 타입이므로, 다른 캘린더로 확장할 수 있도록 리팩터링 필요
해당 부분은 추후 다른 외부 캘린더의 형식을 살펴보고 리팩터링을 진행할 예정으로 이번 PR에서는 넘어가도록 하겠습니다.

2024-09-05 01:23 UTC, JJ503 commented on src/main/java/com/fixadate/global/exception/ControllerAdvice.java
> +	// TODO: [질문] validate 등 예외가 발생헀을 때에 대해서인데 code를 자체적인 번호로 부여해줘야 할까요?
마이너스는 어떤 의미일까요?

2024-09-05 01:24 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/dto/response/AdateViewResponse.java
> +// TODO: [질문] 연동규격서에서는 tagResponse가 없던데 괜찮은가요?
해당 부분 추가해주시면 감사하겠습니다!

2024-09-05 05:37 UTC, YongGoose commented on src/test/java/com/fixadate/domain/adate/service/AdateServiceTest.java
넵 유지하시면 될 것 같습니다.

2024-09-05 05:50 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/controller/impl/AdateControllerImpl.java
> +		// TODO: [질문] service에서 save한 member 객체로 응답값을 만들어 반환하는 것이 더 적절할까요?
Service 레이어에서 반환된 정보를 활용해 응답값을 만드는 것이 더 적절할 것 같네요!

2024-09-05 05:56 UTC, YongGoose commented on src/main/java/com/fixadate/global/exception/ControllerAdvice.java
> +	// TODO: [질문] validate 등 예외가 발생헀을 때에 대해서인데 code를 자체적인 번호로 부여해줘야 할까요?
큰 의미는 없고 단지 + (개발자가 던진 예외)와 구분짓기 위해서 상반된 값을 제안 드렸습니다!

2024-09-05 06:00 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/entity/Adate.java
> +	// TODO: [추후] 구글 캘린더에서 수정이 될 때 ifAllDay, alertWhen, repeatFreq은 수정이 안 되나요? -> 답변 필요
기획팀에서 Fixadate의 알람과 Google Calendar의 알람을 구분짓자고 해서 수정 / 저장이 안 되도록 하였습니다!
> repeatFreq의 경우 삭제될 필드이기 때문에 설명하지 않겠습니다.

2024-09-05 06:02 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/mapper/AdateMapper.java
> +					.color(event.getColorId())
모두 변경하면 될 것 같습니다!
`AdateMapper`의 77, 92번째 줄을 삭제하면 될 것 같네요!

2024-09-08 14:26 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/controller/impl/AdateControllerImpl.java
> +		// TODO: [질문] service에서 save한 member 객체로 응답값을 만들어 반환하는 것이 더 적절할까요?
해당 방식으로 수정하도록 하겠습니다!

2024-09-08 14:27 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/mapper/AdateMapper.java
> +					.color(event.getColorId())
확인했습니다. color 설정은 모두 제거하도록 하겠습니다.

2024-09-08 14:27 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/entity/Adate.java
> +	// TODO: [추후] 구글 캘린더에서 수정이 될 때 ifAllDay, alertWhen, repeatFreq은 수정이 안 되나요? -> 답변 필요
버전 1 배포 후 다시 한 번 이야기해 불필요한 필드는 제거하는 방향으로 진행하도록 하겠습니다.

2024-09-08 14:28 UTC, JJ503 commented on src/main/java/com/fixadate/global/exception/ControllerAdvice.java
> +	// TODO: [질문] validate 등 예외가 발생헀을 때에 대해서인데 code를 자체적인 번호로 부여해줘야 할까요?
그렇다면 명확히 정한 뒤 적용하는 게 좋을 것 같은데 어떻게 생각하시나요?
프론트 측과의 논의는 필요 없을지 궁금합니다!

2024-09-08 14:30 UTC, JJ503 commented on src/main/java/com/fixadate/global/exception/ControllerAdvice.java
> +	// TODO: [질문] validate 등 예외가 발생헀을 때에 대해서인데 code를 자체적인 번호로 부여해줘야 할까요?
`handleConstraintViolationException`, `handleMethodArgumentNotValid`, `handleExceptionInternal`의 경우 기존 상태코드를 code로 사용하고 있습니다.

2024-09-08 14:32 UTC, JJ503 commented on src/main/java/com/fixadate/domain/adate/mapper/AdateMapper.java
> +					.color(event.getColorId())
기존 adate의 로직에서 `updateFrom`의 경우 color도 수정하고 있음을 확인할 수 있습니다.
그렇다면, 수정 시 color는 수정하지 않도록 제거 해야 할까요?
현재 로직에서 adateMapper만 수정하게 된다면 color가 null 값으로 들어갈 것 같네요.

2024-09-08 23:38 UTC, YongGoose commented on src/main/java/com/fixadate/domain/adate/mapper/AdateMapper.java
> +					.color(event.getColorId())
`updateFrom`에서도 수정하지 않도록 제거해야 할 것 같네요.
color가 Null 값으로 들어가도 하기 로직에서 color를 설정해서 상관 없을 것 같습니다.
이 외 사이드 이펙트가 발생할 수 있는 경우가 있다면 코멘트 남겨주세요!
```
applicationEventPublisher.publishEvent(new TagSettingEvent(adate, member, GOOGLE_CALENDAR.getValue()));
```

2024-09-08 23:42 UTC, YongGoose commented on src/main/java/com/fixadate/global/exception/ControllerAdvice.java
> +	// TODO: [질문] validate 등 예외가 발생헀을 때에 대해서인데 code를 자체적인 번호로 부여해줘야 할까요?
> 그렇다면 명확히 정한 뒤 적용하는 게 좋을 것 같은데 어떻게 생각하시나요?

좋습니다! 

> 프론트 측과의 논의는 필요 없을지 궁금합니다!

프론트 측과 논의까지는 할 필요가 없을 것 같습니다!
저번에도 영현님과 비슷한 주제에 대해 얘기를 나눠보았는데 보통 백엔드에서 설정을 한 뒤 통보를 하는 식으로 진행한다고 합니다!

2024-09-08 23:45 UTC, YongGoose commented on src/main/java/com/fixadate/global/exception/ControllerAdvice.java
> +	// TODO: [질문] validate 등 예외가 발생헀을 때에 대해서인데 code를 자체적인 번호로 부여해줘야 할까요?
다른 예외의 경우 제가 주석을 통해 코드 값 범위를 정했습니다!
스프링이 던진 예외도 범위를 정해서 진행하면 좋을 듯 하네요.
**주석을 다시 살펴본 결과 -(마이너스)가 아닌 other -> 9xxx에 배정하는 것도 괜찮을 것 같네요 :)**
```
	/*
	adate -> 1xxx
	tag -> 2xxx
	googleCalendar -> 3xxx
	member -> 4xxx

	team -> 7xxx
	auth -> 8xxx
	other -> 9xxx
	 */
```

2024-09-13 00:09 UTC, YongGoose approved these changes
고생하셨습니다!
모든 대화가 해결되어 Approve 합니다!

2024-09-16 02:08 UTC, merged